Traceback (most recent call last):
  File "/Users/daniel/Library/Caches/pypoetry/virtualenvs/rangekeeperwalkthrough-3n9gAvA9-py3.11/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/daniel/Library/Caches/pypoetry/virtualenvs/rangekeeperwalkthrough-3n9gAvA9-py3.11/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daniel/Library/Caches/pypoetry/virtualenvs/rangekeeperwalkthrough-3n9gAvA9-py3.11/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daniel/.pyenv/versions/3.11.8/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/daniel/Library/Caches/pypoetry/virtualenvs/rangekeeperwalkthrough-3n9gAvA9-py3.11/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/daniel/Library/Caches/pypoetry/virtualenvs/rangekeeperwalkthrough-3n9gAvA9-py3.11/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/daniel/Library/Caches/pypoetry/virtualenvs/rangekeeperwalkthrough-3n9gAvA9-py3.11/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Define a Span:
start_date = pd.Timestamp('2001-01-01')
num_periods = 11
span = rk.span.Span.from_num_periods(
    name='Operation',
    date=start_date,
    period_type=rk.periodicity.Type.YEAR,
    num_periods=num_periods)
print(span)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[9], line 4[0m
[1;32m      2[0m start_date [38;5;241m=[39m pd[38;5;241m.[39mTimestamp([38;5;124m'[39m[38;5;124m2001-01-01[39m[38;5;124m'[39m)
[1;32m      3[0m num_periods [38;5;241m=[39m [38;5;241m11[39m
[0;32m----> 4[0m span [38;5;241m=[39m [43mrk[49m[38;5;241;43m.[39;49m[43mspan[49m[38;5;241;43m.[39;49m[43mSpan[49m[38;5;241;43m.[39;49m[43mfrom_num_periods[49m(
[1;32m      5[0m     name[38;5;241m=[39m[38;5;124m'[39m[38;5;124mOperation[39m[38;5;124m'[39m,
[1;32m      6[0m     date[38;5;241m=[39mstart_date,
[1;32m      7[0m     period_type[38;5;241m=[39mrk[38;5;241m.[39mperiodicity[38;5;241m.[39mType[38;5;241m.[39mYEAR,
[1;32m      8[0m     num_periods[38;5;241m=[39mnum_periods)
[1;32m      9[0m [38;5;28mprint[39m(span)

[0;31mAttributeError[0m: type object 'Span' has no attribute 'from_num_periods'

