Traceback (most recent call last):
  File "/Users/daniel/Library/Caches/pypoetry/virtualenvs/rangekeeperwalkthrough-3n9gAvA9-py3.11/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/daniel/Library/Caches/pypoetry/virtualenvs/rangekeeperwalkthrough-3n9gAvA9-py3.11/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daniel/Library/Caches/pypoetry/virtualenvs/rangekeeperwalkthrough-3n9gAvA9-py3.11/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daniel/.pyenv/versions/3.11.8/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/daniel/Library/Caches/pypoetry/virtualenvs/rangekeeperwalkthrough-3n9gAvA9-py3.11/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/daniel/Library/Caches/pypoetry/virtualenvs/rangekeeperwalkthrough-3n9gAvA9-py3.11/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/daniel/Library/Caches/pypoetry/virtualenvs/rangekeeperwalkthrough-3n9gAvA9-py3.11/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
period_type = rk.periodicity.Type.YEAR
span = rk.span.Span.from_num_periods(
    name="Span",
    date=pd.Timestamp(2000, 1, 1),
    period_type=period_type,
    num_periods=25)
sequence = span.to_index(period_type=period_type)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[4], line 1[0m
[0;32m----> 1[0m period_type [38;5;241m=[39m [43mrk[49m[38;5;241;43m.[39;49m[43mperiodicity[49m[38;5;241m.[39mType[38;5;241m.[39mYEAR
[1;32m      2[0m span [38;5;241m=[39m rk[38;5;241m.[39mspan[38;5;241m.[39mSpan[38;5;241m.[39mfrom_num_periods(
[1;32m      3[0m     name[38;5;241m=[39m[38;5;124m"[39m[38;5;124mSpan[39m[38;5;124m"[39m,
[1;32m      4[0m     date[38;5;241m=[39mpd[38;5;241m.[39mTimestamp([38;5;241m2000[39m, [38;5;241m1[39m, [38;5;241m1[39m),
[1;32m      5[0m     period_type[38;5;241m=[39mperiod_type,
[1;32m      6[0m     num_periods[38;5;241m=[39m[38;5;241m25[39m)
[1;32m      7[0m sequence [38;5;241m=[39m span[38;5;241m.[39mto_index(period_type[38;5;241m=[39mperiod_type)

[0;31mAttributeError[0m: module 'rangekeeper' has no attribute 'periodicity'

